apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: git-input-artifact
  namespace: argo
spec:
  entrypoint: git-clone
  serviceAccountName: argo
  arguments:
    parameters:
      - name: git-repo-path
        value: "{{ tpl (required "value 'git.path' required" .Values.git.path) $ }}"
      - name: git-repo-url
        value: "{{ tpl (required "value 'git.repo' required" .Values.git.repo) $ }}"
      - name: git-secret-name
        value: "{{ tpl (required "value 'secretName' required" .Values.secretName) $ }}"
      - name: git-repo-revision
        value: "{{ tpl (required "value 'git.branch' required" .Values.git.branch) $ }}"
  volumeClaimTemplates:
    - metadata:
        name: workdir
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi
  templates:
  - name: git-clone
    inputs:
      artifacts:
        - name: argo-source
          path: '{{ printf "/gen-source{{workflow.parameters.git-repo-path}}" }}'
          git:
            repo: '{{ printf "https://{{workflow.parameters.git-repo-url}}" }}'
            revision: '{{ printf "{{workflow.parameters.git-repo-revision}}" }}'
            usernameSecret:
              name: '{{ printf "{{workflow.parameters.git-secret-name}}" }}'
              key: username
            passwordSecret:
              name: '{{ printf "{{workflow.parameters.git-secret-name}}" }}'
              key: password
    container:
      image: alpine/git
      command: [sh, -c]
      args: ["git status && ls && cat README.md"]
      workingDir: '{{ printf "/gen-source{{workflow.parameters.git-repo-path}}" }}'
      volumeMounts:
        - name: workdir
          mountPath: /gen-source
